[2023-03-07 12:08:35,171] {processor.py:153} INFO - Started process (PID=40758) to work on /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
[2023-03-07 12:08:35,172] {processor.py:641} INFO - Processing file /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py for tasks to queue
[2023-03-07 12:08:35,172] {logging_mixin.py:115} INFO - [2023-03-07 12:08:35,172] {dagbag.py:507} INFO - Filling up the DagBag from /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
[2023-03-07 12:08:35,182] {logging_mixin.py:115} INFO - [2023-03-07 12:08:35,182] {dagbag.py:320} ERROR - Failed to import: /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
Traceback (most recent call last):
  File "/home/veri-pc/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py", line 4, in <module>
    from server.config.db import MongoConnection
ModuleNotFoundError: No module named 'server'
[2023-03-07 12:08:35,183] {processor.py:653} WARNING - No viable dags retrieved from /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
[2023-03-07 12:08:35,199] {processor.py:161} INFO - Processing /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py took 0.031 seconds
[2023-03-07 12:09:09,327] {processor.py:153} INFO - Started process (PID=40849) to work on /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
[2023-03-07 12:09:09,328] {processor.py:641} INFO - Processing file /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py for tasks to queue
[2023-03-07 12:09:09,330] {logging_mixin.py:115} INFO - [2023-03-07 12:09:09,329] {dagbag.py:507} INFO - Filling up the DagBag from /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
[2023-03-07 12:09:09,348] {logging_mixin.py:115} INFO - [2023-03-07 12:09:09,347] {dagbag.py:320} ERROR - Failed to import: /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
Traceback (most recent call last):
  File "/home/veri-pc/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py", line 4, in <module>
    from server.config.db import MongoConnection
ModuleNotFoundError: No module named 'server'
[2023-03-07 12:09:09,348] {processor.py:653} WARNING - No viable dags retrieved from /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
[2023-03-07 12:09:09,365] {processor.py:161} INFO - Processing /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py took 0.044 seconds
[2023-03-07 12:09:43,021] {processor.py:153} INFO - Started process (PID=40942) to work on /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
[2023-03-07 12:09:43,021] {processor.py:641} INFO - Processing file /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py for tasks to queue
[2023-03-07 12:09:43,022] {logging_mixin.py:115} INFO - [2023-03-07 12:09:43,022] {dagbag.py:507} INFO - Filling up the DagBag from /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
[2023-03-07 12:09:43,027] {logging_mixin.py:115} INFO - [2023-03-07 12:09:43,027] {dagbag.py:320} ERROR - Failed to import: /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
Traceback (most recent call last):
  File "/home/veri-pc/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py", line 4, in <module>
    from server.config.db import MongoConnection
ModuleNotFoundError: No module named 'server'
[2023-03-07 12:09:43,027] {processor.py:653} WARNING - No viable dags retrieved from /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
[2023-03-07 12:09:43,037] {processor.py:161} INFO - Processing /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py took 0.018 seconds
[2023-03-07 12:10:21,753] {processor.py:153} INFO - Started process (PID=41028) to work on /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
[2023-03-07 12:10:21,754] {processor.py:641} INFO - Processing file /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py for tasks to queue
[2023-03-07 12:10:21,755] {logging_mixin.py:115} INFO - [2023-03-07 12:10:21,755] {dagbag.py:507} INFO - Filling up the DagBag from /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
[2023-03-07 12:10:21,763] {logging_mixin.py:115} INFO - [2023-03-07 12:10:21,762] {dagbag.py:320} ERROR - Failed to import: /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
Traceback (most recent call last):
  File "/home/veri-pc/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py", line 4, in <module>
    from server.config.db import MongoConnection
ModuleNotFoundError: No module named 'server'
[2023-03-07 12:10:21,763] {processor.py:653} WARNING - No viable dags retrieved from /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
[2023-03-07 12:10:21,774] {processor.py:161} INFO - Processing /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py took 0.025 seconds
[2023-03-07 12:10:58,369] {processor.py:153} INFO - Started process (PID=41121) to work on /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
[2023-03-07 12:10:58,370] {processor.py:641} INFO - Processing file /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py for tasks to queue
[2023-03-07 12:10:58,371] {logging_mixin.py:115} INFO - [2023-03-07 12:10:58,371] {dagbag.py:507} INFO - Filling up the DagBag from /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
[2023-03-07 12:10:58,389] {logging_mixin.py:115} INFO - [2023-03-07 12:10:58,388] {dagbag.py:320} ERROR - Failed to import: /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
Traceback (most recent call last):
  File "/home/veri-pc/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py", line 4, in <module>
    from server.config.db import MongoConnection
ModuleNotFoundError: No module named 'server'
[2023-03-07 12:10:58,390] {processor.py:653} WARNING - No viable dags retrieved from /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
[2023-03-07 12:10:58,406] {processor.py:161} INFO - Processing /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py took 0.044 seconds
[2023-03-07 12:12:09,172] {processor.py:153} INFO - Started process (PID=41412) to work on /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
[2023-03-07 12:12:09,173] {processor.py:641} INFO - Processing file /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py for tasks to queue
[2023-03-07 12:12:09,175] {logging_mixin.py:115} INFO - [2023-03-07 12:12:09,174] {dagbag.py:507} INFO - Filling up the DagBag from /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
[2023-03-07 12:12:09,188] {logging_mixin.py:115} INFO - [2023-03-07 12:12:09,186] {dagbag.py:320} ERROR - Failed to import: /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
Traceback (most recent call last):
  File "/home/veri-pc/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py", line 4, in <module>
    from server.config.db import MongoConnection
ModuleNotFoundError: No module named 'server'
[2023-03-07 12:12:09,189] {processor.py:653} WARNING - No viable dags retrieved from /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
[2023-03-07 12:12:09,211] {processor.py:161} INFO - Processing /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py took 0.046 seconds
[2023-03-07 12:12:45,772] {processor.py:153} INFO - Started process (PID=41516) to work on /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
[2023-03-07 12:12:45,776] {processor.py:641} INFO - Processing file /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py for tasks to queue
[2023-03-07 12:12:45,778] {logging_mixin.py:115} INFO - [2023-03-07 12:12:45,778] {dagbag.py:507} INFO - Filling up the DagBag from /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
[2023-03-07 12:12:45,791] {logging_mixin.py:115} INFO - [2023-03-07 12:12:45,790] {dagbag.py:320} ERROR - Failed to import: /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
Traceback (most recent call last):
  File "/home/veri-pc/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py", line 4, in <module>
    from server.config.db import MongoConnection
ModuleNotFoundError: No module named 'server'
[2023-03-07 12:12:45,792] {processor.py:653} WARNING - No viable dags retrieved from /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py
[2023-03-07 12:12:45,877] {processor.py:161} INFO - Processing /home/veri-pc/Documentos/projeto_airflow/dags/cotacao_dolar.py took 0.112 seconds
